min_version = "2024.9.5"

[env]
PROJECT_NAME = "{{ config_root | basename }}"

_.python.venv = { path = ".venv", create = true }

[tools]
python = "{{ get_env(name='PYTHON_VERSION', default='3.13.2') }}"
ruff = "latest"

[tasks.install]
description = "Install dependencies"
alias = "i"
run = "uv pip install -r requirements_test.txt"

